federation_version: =2.8.1
subgraphs:
  book:
    routing_url: http://localhost:4001/graphql
    schema:
      file: ./schema.graphql
  library:
    routing_url: http://localhost:4002/graphql
    schema:
      file: ../LibraryApi/schema.graphql